version: "3"
services:
  go-parser:
    container_name: go-parser
    image: golang:1.13
    volumes:
      - ~/wiki-blog/content:/vimwiki
      - ./:/src/
      - ./result/:/result
    environment:
      - CSV_PATH=/result/tags.csv
      - VIMWIKI=/vimwiki
    working_dir: /src/parsing
    command: go test

  content-recommender:
    build: ./recommender
    command: python3 recommender_system.py
    volumes:
      - ./result:/result
    environment:
      - CSV_PATH=/result/tags.csv
    depends_on:
      - go-parser
